name: hyp3-mintpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.12
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - geopandas
  - hyp3lib>=3,<4
  - hyp3_sdk
  - mintpy==1.6.2
  - rasterio
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
